import Head from "next/head";
import styled from "@emotion/styled";
import Publish from "../components/Home/Publish";
import PostList from "../components/Home/PostList";

export default function Home() {
	return (
		<HomeGlobal>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<br />
			<Publish />
			<br />
			<PostList />
			<br />
		</HomeGlobal>
	);
}

const HomeGlobal = styled.div`
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	background-color: rgb(240, 240, 240);
`;
